--SELECT 기본형식
--SELECT 컬럼1, 컬럼2....from 테이블명 where 검색조건식 
-- order by 기준컬럼(기본은 오름 :asc, 내림: desc)

SELECT*FROM TBL_BUY tb ; -- INSERT 실행한 순서로 결과 출력
SELECT *FROM TBL_CUSTOM tc ;
SELECT *FROM TBL_CUSTOM tc ORDER BY CUSTOM_ID ;
SELECT *FROM TBL_BUY tb WHERE CUSTOM_ID = 'mina012';
SELECT *FROM TBL_BUY tb WHERE CUSTOM_ID = 'mina012'
					ORDER BY BUY_DATE DESC;	--WHERE 먼저 order BY 순서 지킵니다
					
-- 조회할 컬럼을 지정할 때 DISTINCT 키워드 : 중복값은 1번만 결과 출력.
SELECT custom_Id FROM TBL_BUY tb ;	-- 구매고객 ID조회
SELECT DISTINCT custom_Id FROM TBL_BUY tb ; -- 중복값은 1번만

-- 6/30 복습문제
SELECT*FROM tbl_custom WHERE age >= 30;
SELECT EMAIL FROM TBL_CUSTOM WHERE CUSTOM_ID = 'twice';
SELECT PNAME  FROM TBL_PRODUCT WHERE CATEGORY ='A2';
SELECT max(price) FROM TBL_PRODUCT;
SELECT sum(quantity) FROM TBL_BUY WHERE PCODE = 'IPAD011';
SELECT PCODe FROM TBL_BUY WHERE CUSTOM_ID = 'mina012';
SELECT*FROM TBL_BUY WHERE PCODE LIKE '%0%'

SELECT*FROM TBL_BUY WHERE UPPER(PCODE) LIKE '%ON%';
SELECT*FROM TBL_BUY WHERE LOWER(PCODE) LIKE '%on%';